# Generated by Django 2.1.7 on 2019-02-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20190216_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='main_pics'),
        ),
        migrations.AddField(
            model_name='tour',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
